import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "both"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Retina" }
size = 15
