format = """
[](#FEA7E5)\
$username\
[](fg:#FEA7E5 bg:#FFFA60)\
$directory\
[](fg:#FFFA60 bg:#00F4FF)\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nim\
$rust\
$nodejs\
[ ](fg:#00F4FF)\
"""

# removed from above:
# [](fg:#FFFA60 bg:#00F4FF)\
# $nodejs\
# $time\
# [ ](fg:#00F4FF)\

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#FEA7E5 fg:#313345"
style_root = "bg:#FEA7E5"
format = '[>_ ]($style)'


[directory]
style = "bg:#FFFA60 fg:#313345"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"code" = ""
"derome" = ""
"backend" = "ﬦ"
"infrastructure" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#1F4E50"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#1F4E50"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#1F4E50"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#00F4FF fg:#313345"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#00F4FF fg:#313345"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#1F4E50"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#1F4E50"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#1F4E50"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#1F4E50"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#00F4FF fg:#313345"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#1F4E50"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#00F4FF fg:#313345"
format = '[ $symbol ($version) ]($style)'

# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#1F4E50"
# format = '[ ♥ $time ]($style)'

[time]
disabled = false
time_format = "%R"              # Hour:Minute Format
style = "bg:#00F4FF fg:#313345"
format = '[  $time ]($style)'
